<#
.SYNOPSIS
    Smart Ops - GitHub Automation Script (PowerShell)
    Generated by /init_smart_ops workflow

.EXAMPLE
    .\scripts\smart-ops.ps1 start
    .\scripts\smart-ops.ps1 create "Fix bug" "Description" "bug" 3
#>

param(
    [Parameter(Position=0)]
    [string]$Command = "help",
    
    [Parameter(Position=1)]
    [string]$Arg1 = "",
    
    [Parameter(Position=2)]
    [string]$Arg2 = "",
    
    [Parameter(Position=3)]
    [string]$Arg3 = "",
    
    [Parameter(Position=4)]
    [int]$Arg4 = 7
)

$ErrorActionPreference = "Stop"

# ============ CONFIGURATION ============
$REPO_OWNER = "JStaRFilms"
$REPO_NAME = "LinkForge"
$REPO = "$REPO_OWNER/$REPO_NAME"

# GitHub Projects Integration
$PROJECT_NUMBER = "5"
$PROJECT_ID = "PVT_kwHOBryib84BKfpM"
$STATUS_FIELD_ID = "PVTSSF_lAHOBryib84BKfpMzg6WIzc"
$TODO_OPTION_ID = "f75ad846"
$IN_PROGRESS_OPTION_ID = "47fc9ee4"
$DONE_OPTION_ID = "98236657"

$START_DATE_FIELD_ID = "PVTF_lAHOBryib84BKfpMzg6WI10"
$TARGET_DATE_FIELD_ID = "PVTF_lAHOBryib84BKfpMzg6WI14"

$DEBUG = $env:DEBUG -eq "1"

# ============ PREREQUISITES ============

function Test-Prerequisites {
    $errors = 0
    
    try { $null = Get-Command gh -ErrorAction Stop }
    catch {
        Write-Host "X GitHub CLI not installed: https://cli.github.com" -ForegroundColor Red
        $errors++
    }
    
    try {
        $null = gh auth status 2>&1
        if ($LASTEXITCODE -ne 0) { throw }
    } catch {
        Write-Host "X Not authenticated. Run: gh auth login" -ForegroundColor Red
        $errors++
    }
    
    if ([string]::IsNullOrWhiteSpace($REPO_OWNER) -or [string]::IsNullOrWhiteSpace($REPO_NAME)) {
        Write-Host "X REPO_OWNER and REPO_NAME must be set" -ForegroundColor Red
        $errors++
    }
    
    if ($errors -gt 0) { exit 1 }
}

# ============ HELPERS ============

function Write-DebugMsg { param([string]$Msg) if ($script:DEBUG) { Write-Host "[DEBUG] $Msg" -ForegroundColor Gray } }
function Write-Err { param([string]$Msg) Write-Host "X $Msg" -ForegroundColor Red }
function Write-Ok { param([string]$Msg) Write-Host "[OK] $Msg" -ForegroundColor Green }

function Get-Today { return (Get-Date -Format "yyyy-MM-dd") }
function Get-FutureDate { param([int]$Days = 7); return (Get-Date).AddDays($Days).ToString("yyyy-MM-dd") }

function Invoke-GH {
    param([string[]]$GhArgs)
    Write-DebugMsg "gh $($GhArgs -join ' ')"
    try {
        $output = & gh @GhArgs 2>&1
        if ($LASTEXITCODE -ne 0) { throw "Exit code $LASTEXITCODE" }
        return $output
    } catch {
        Write-Err "Command failed: gh $($GhArgs -join ' ')"
        throw
    }
}

# ============ COMMANDS ============

function Start-Scan {
    Write-Host "[SCAN] Scanning work..." -ForegroundColor Cyan
    $issues = Invoke-GH @("issue", "list", "--repo", $script:REPO, "--state", "open", "--json", "number,title,labels", "--limit", "20")
    Write-Host $issues
    
    if (![string]::IsNullOrWhiteSpace($script:PROJECT_NUMBER)) {
        Write-Host ""
        Write-Host "[PROJECT] Project items:" -ForegroundColor Cyan
        try { 
            $items = & gh project item-list $script:PROJECT_NUMBER --owner $script:REPO_OWNER --format json --limit 20 2>$null
            Write-Host $items
        } catch { }
    }
}

function Complete-Scan {
    Write-Host "[COMPLETE] Ready for completion..." -ForegroundColor Cyan
    $issues = Invoke-GH @("issue", "list", "--repo", $script:REPO, "--state", "open", "--json", "number,title", "--limit", "20")
    Write-Host $issues
    Write-Host ""
    Write-Host "Today: $(Get-Today)"
    Write-Host 'Close with: .\scripts\smart-ops.ps1 close [number]' -ForegroundColor Gray
}

function New-Issue {
    param(
        [string]$Title,
        [string]$Body = "",
        [string]$Labels = "enhancement",
        [int]$Days = 7
    )
    
    if ([string]::IsNullOrWhiteSpace($Title)) {
        Write-Err "Title required"
        return
    }
    
    Write-Host "[CREATE] Creating: $Title ($Days days)" -ForegroundColor Cyan
    
    $url = Invoke-GH @("issue", "create", "--repo", $script:REPO, "--title", $Title, "--body", $Body, "--label", $Labels)
    
    if ($url -match '/(\d+)$') {
        $num = $Matches[1]
        Write-Ok "Created #$num"
        
        if (![string]::IsNullOrWhiteSpace($script:PROJECT_ID)) {
            try {
                $itemId = & gh project item-add $script:PROJECT_NUMBER --owner $script:REPO_OWNER --url $url --format json --jq '.id'
                
                if (![string]::IsNullOrWhiteSpace($script:START_DATE_FIELD_ID)) {
                    & gh project item-edit --id $itemId --project-id $script:PROJECT_ID --field-id $script:START_DATE_FIELD_ID --date (Get-Today) 2>$null
                }
                if (![string]::IsNullOrWhiteSpace($script:TARGET_DATE_FIELD_ID)) {
                    & gh project item-edit --id $itemId --project-id $script:PROJECT_ID --field-id $script:TARGET_DATE_FIELD_ID --date (Get-FutureDate -Days $Days) 2>$null
                }
                Write-Ok "Added to project"
            } catch {
                Write-Err "Failed to add to project"
            }
        }
        Write-Host $url
    }
}

function Close-Issue {
    param([string]$Num, [string]$Comment = "Completed")
    
    if ([string]::IsNullOrWhiteSpace($Num)) {
        Write-Err "Issue number required"
        return
    }
    
    $confirm = Read-Host "Close #$Num ? (y/N)"
    if ($confirm -ne 'y') { return }
    
    Invoke-GH @("issue", "close", $Num, "--repo", $script:REPO, "--comment", $Comment)
    Write-Ok "Closed #$Num"
}

function Move-ToProgress {
    param([string]$Id)
    
    if ([string]::IsNullOrWhiteSpace($script:PROJECT_ID)) {
        Write-Err "No project configured"
        return
    }
    if ([string]::IsNullOrWhiteSpace($Id)) {
        Write-Err "Item ID required"
        return
    }
    
    & gh project item-edit --id $Id --field-id $script:STATUS_FIELD_ID --project-id $script:PROJECT_ID --single-select-option-id $script:IN_PROGRESS_OPTION_ID
    
    if (![string]::IsNullOrWhiteSpace($script:START_DATE_FIELD_ID)) {
        & gh project item-edit --id $Id --project-id $script:PROJECT_ID --field-id $script:START_DATE_FIELD_ID --date (Get-Today) 2>$null
    }
    Write-Ok "-> In Progress"
}

function Move-ToDone {
    param([string]$Id)
    
    if ([string]::IsNullOrWhiteSpace($script:PROJECT_ID)) {
        Write-Err "No project configured"
        return
    }
    if ([string]::IsNullOrWhiteSpace($Id)) {
        Write-Err "Item ID required"
        return
    }
    
    & gh project item-edit --id $Id --field-id $script:STATUS_FIELD_ID --project-id $script:PROJECT_ID --single-select-option-id $script:DONE_OPTION_ID
    Write-Ok "-> Done"
}

function Show-Help {
    $helpText = @"
Smart Ops - GitHub Automation

Usage: .\scripts\smart-ops.ps1 [command] [args]

Commands:
  start                      List open issues
  complete                   List for completion
  create [title] [body] [labels] [days]
  close [number] [comment]
  progress [item_id]         Move to In Progress
  done [item_id]             Move to Done

Examples:
  .\scripts\smart-ops.ps1 create "Fix bug" "Description" "bug" 3
  .\scripts\smart-ops.ps1 close 42 "Fixed"
  `$env:DEBUG=1; .\scripts\smart-ops.ps1 start
"@
    Write-Host $helpText -ForegroundColor Cyan
}

# ============ MAIN ============

Test-Prerequisites

try {
    switch ($Command.ToLower()) {
        "start" { Start-Scan }
        "complete" { Complete-Scan }
        "create" { 
            $labels = if ($Arg3) { $Arg3 } else { "enhancement" }
            New-Issue -Title $Arg1 -Body $Arg2 -Labels $labels -Days $Arg4 
        }
        "close" { 
            $comment = if ($Arg2) { $Arg2 } else { "Completed" }
            Close-Issue -Num $Arg1 -Comment $comment 
        }
        "progress" { Move-ToProgress -Id $Arg1 }
        "done" { Move-ToDone -Id $Arg1 }
        default { Show-Help }
    }
} catch {
    Write-Host ""
    Write-Err "Failed: $_"
    exit 1
}
